### ISSUE TITLE
Bad Performance: Frame skipping when running 496 mods

### ISSUE THREAD

**Issue by zwei7** [Steviegt6/Stardew64Installer#19] opened 2021-05-31 17:11 UTC
When walking at stock speeds or running with 7x move speed (CJB cheats menu mod), my farmer character's walk/run animation is skipping frames, so is the whole map. Occurs whether v-sync is on or off and in windowed mode. The screen is not tearing apart horizontally.

My PC can handle it just fine when running Stardew 32 bit with SMAPI 3.10 with the same mods.
My PC is an Intel i5 8600K, 32 GB ram, and an RX 580 8GB.

**Comment by Pathoschild** [comment] 2021-06-11 00:03
Hi! There's no need to start a new bug report for each update, you can just add comments to your first one. I'll close this as a duplicate of #21, since the most informative one.

**Closed as completed by Pathoschild** 2021-06-11 00:03 UTC
Labels: duplicate
