### ISSUE TITLE
Game crashes loading 0 mods

### ISSUE THREAD

**Issue by zwei7** [Steviegt6/Stardew64Installer#23] opened 2021-06-02 23:03 UTC
Smapi can't even log the crash.
https://smapi.io/log/ad876e75c2b74feaa023382e3dc38ed0

Started the game with the default "Mods" folder with the 3 default included add-ons.
Crashes after the concerned ape logo appears.

**Comment by Pathoschild** [comment] 2021-06-11 00:02
Hi! There's no need to start a new bug report for each update, you can just add comments to your first one. I'll close this as a duplicate of #21.

**Closed as completed by Pathoschild** 2021-06-11 00:02 UTC
Labels: duplicate
