### ISSUE TITLE
Game crashes when attempting to start a new game

### ISSUE THREAD

**Issue by zwei7** [Steviegt6/Stardew64Installer#22] opened 2021-05-31 19:26 UTC
Crashes after pressing "Co-op" Button

Crashes after pressing "OK" after selecting "New" single player game (named character, farm, and favourite thing "1", checkmarked skip intro, left all other options default)
https://smapi.io/log/5670875e5cf54c708a63f840d303ebe2

Then it worked twice

Then this happened, may because I kept naming everything "1". (named character, farm, and favourite thing "1", checkmarked skip intro, left all other options default)
https://smapi.io/log/51bd00459ef04c5594727f72ae2e7be6

Started game again and when I pressing the blue sky so I could change focus into the game and press "new" it closed itself. Not driver time out error. Just exited itself. No smapi error was reported.
https://smapi.io/log/3d5805524f704fa9bd4d8753fa0a5973

**Comment by Pathoschild** [comment] 2021-06-11 00:02
Hi! There's no need to start a new bug report for each update, you can just add comments to your first one. I'll close this as a duplicate of #21.

**Closed as completed by Pathoschild** 2021-06-11 00:02 UTC
Labels: duplicate
