### ISSUE TITLE
Games crashes after renaming mods folder

### ISSUE THREAD

**Issue by zwei7** [Steviegt6/Stardew64Installer#20] opened 2021-05-31 17:22 UTC
The game ran fine with 400+ mods.

But wih the frame skipping issues I thought less mods would improve it. I renamed the mods folder into "Mods1" so the game would start up with 0 mods to see if it would reduce frame skipping. Game created another folder called Mods.  The game ran much smoother in the title menu screen (New, Load, co-op, exit). I clicked co-op, said "connecting to online services", then crashed. Weird.

When loading 0 mods the game also crashes when I start a new game and type a few letters to name my farmer character.
https://smapi.io/log/b756dd3ec8fa4451be9223e398a6fb96

I deleted that folder newly created empty "Mods" and renamed "Mods1" back into "Mods" so it would load the mods back in.
When loading 400+ mods the game crashes
https://smapi.io/log/49ed9653dc1341f18179140267df51dc

I guess I have to extract a gog linux installer and use the windows installer on it again to create a new working copy.

**Comment by Pathoschild** [comment] 2021-06-11 00:01
Hi! There's no need to start a new bug report for each update, you can just add comments to your first one. I'll close this as a duplicate of #21, since that's the most informative one.

**Closed as completed by Pathoschild** 2021-06-11 00:01 UTC
Labels: duplicate
