### ISSUE TITLE
Driver Timeout with 82 mods

### ISSUE THREAD

**Issue by zwei7** [Steviegt6/Stardew64Installer#24] opened 2021-06-05 17:30 UTC
**Driver Timeout Error**
Driver Timeout Error (screen goes black) when using 64-Bit Stardew on Windows 10 64-bit, Intel i5, Radeon RX 580 8 GB

**To Reproduce**
1. Load game with Mods (This 82 or 29 combination produces this error 100% of the time)
2. Click CO-OP
3. Driver Time-out and on rare ocassions the game closes/exits/alt-f4s itself at this point after clicking CO-OP

**Log file**
Log for Driver Timeout with 82 mods
https://smapi.io/log/dc18af389b5749128232e2040095d5f4

Log for Driver Timeout with 29 mods
https://smapi.io/log/512219a8623948af89f5cbd3cbd05e3c

**Game Exits**
Game turns itself off (the game closes/exits/alt-f4s itself)

**To Reproduce**
1. Load game with Mods (4 default mods + 1 mod, PyTK)
2. Click CO-OP
3. Game closes/exits/alt-f4s itself at this point
4. If not, then create a farmer with the name, farm name, and favorite thing as "1" and skip intro
5. Text for "You are now hosting a Multiplayer Game" Game closes/exits/alt-f4s itself at this point
6. If not you can walk around your house and in a few seconds, Game closes/exits/alt-f4s itself at this point

Log for Driver Timeout with 5 mods
https://smapi.io/log/4d8090a8b015451b8fab58b2cbb36aac

Crazy thing is I had this game running with all the above mods on and a ton of others 365+ mods and it ran fine, but frame skipping performance issue, all the way to Spring Day 13 of Year 1. The above tests did not have frame skipping but timeout errorrs and abrupt exiting/alt-f4

**Comment by Pathoschild** [comment] 2021-06-11 00:02
Hi! There's no need to start a new bug report for each update, you can just add comments to your first one. I'll close this as a duplicate of #21.

**Closed as completed by Pathoschild** 2021-06-11 00:02 UTC
Labels: duplicate
