### ISSUE TITLE
Game Closes or Driver Timout Error after starting a new Multiplayer Game 50 Mods

### ISSUE THREAD

**Issue by zwei7** [Steviegt6/Stardew64Installer#25] opened 2021-06-05 19:44 UTC
**Game Exits / Driver Timout Error**
Game turns itself off (the game closes/exits/alt-f4s itself) or Driver Timout Error (Computer freezes momentarily and screen goes black)

**To Reproduce**
1. Load game with 50 Mods
2. Click CO-OP
3. Game exits, or freezes with mouse cursor unable to move within the game window
4. If not then, Create a farmer with the name, farm name, and favorite thing as "1" and skip intro
5. Game Exits or Driver Time out error

**Log file**
https://smapi.io/log/73187e752d48425f975d1156c7b10aee (Game exits at step 3)
https://smapi.io/log/fa66a453480c4a47b37865555d77fcb2 (Game freezes at step 3)
https://smapi.io/log/0ee157f457764547b89b94bd1bca46ca (Driver Timeout at step 5)

**Comment by Pathoschild** [comment] 2021-06-11 00:03
Hi! There's no need to start a new bug report for each update, you can just add comments to your first one. I'll close this as a duplicate of #21.

**Closed as completed by Pathoschild** 2021-06-11 00:03 UTC
Labels: duplicate
